-- AlterTable
ALTER TABLE "File" ALTER COLUMN "size" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "PromoCode" ALTER COLUMN "maxSpace" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "maxSpace" SET DATA TYPE BIGINT,
ALTER COLUMN "usedSpace" SET DATA TYPE BIGINT;
